version: '3'

services:
    example-client:
        build: ./client/
        container_name: client
        networks:
            - keycloak-network
        ports:
            - "5000:5000"

    keycloak-server:
        image: jboss/keycloak
        # command: /opt/jboss/tools/docker-entrypoint.sh -b 0.0.0.0 -bmanagement 0.0.0.0
        container_name: keycloak
        networks:
            - keycloak-network
        ports:
            - "8080:8080"
            - "8443:8443"
        environment:
            - KEYCLOAK_USER=admin
            - KEYCLOAK_PASSWORD=adminpw
            - DB_USER=keycloak
            - DB_PASSWORD=keycloakpw
            # - KEYCLOAK_HOSTNAME=oai-pmh-test.basisit.de
            # - PROXY_ADDRESS_FORWARDING=true
        # volumes:
        #     - "/net/home/mch/keycloak/certs/:/etc/x509/https"

    mysql-db:
        image: mysql
        container_name: mysql
        networks:
            - keycloak-network
        environment:
            - MYSQL_DATABASE=keycloak
            - MYSQL_USER=keycloak
            - MYSQL_PASSWORD=keycloakpw
            - MYSQL_ROOT_PASSWORD=rootpw
        # volumes:
        #     - /net/home/mch/keycloak/data:/var/lib/mysql

networks:
    keycloak-network:
