version: '3'

services:
    nginx:
        build: .
        container_name: nginx
        ports:
            - '8443:443'
        networks:
            - keycloak-network

    example-client:
        build: ./client/
        container_name: client
        networks:
            - keycloak-network
        ports:
            - "5000:5000"

    keycloak-server:
        image: jboss/keycloak
        container_name: keycloak
        networks:
            - keycloak-network
        ports:
            - "8080:8080"
        environment:
            - KEYCLOAK_USER=admin
            - KEYCLOAK_PASSWORD=adminpw
            - DB_USER=keycloak
            - DB_PASSWORD=keycloakpw
            - PROXY_ADDRESS_FORWARDING=true
            - KEYCLOAK_HOSTNAME=oai-pmh-test.basisit.de

    mysql-db:
        image: mysql
        container_name: mysql
        networks:
            - keycloak-network
        environment:
            - MYSQL_DATABASE=keycloak
            - MYSQL_USER=keycloak
            - MYSQL_PASSWORD=keycloakpw
            - MYSQL_ROOT_PASSWORD=rootpw

networks:
    keycloak-network:
