version: '3'

services:
    client:
        build: ./client/
        container_name: client
        networks:
            - keycloak-network
        ports:
            - "5000:5000"
        volumes:
            - "./client:/app"

    keycloak:
        image: jboss/keycloak
        container_name: keycloak
        networks:
            - keycloak-network
        ports:
            - "8443:8443"
            - "8080:8080"
        environment:
            - KEYCLOAK_USER=admin
            - KEYCLOAK_PASSWORD=admin
            - DB_USER=keycloak
            - DB_PASSWORD=keycloakpw
        volumes:
            - "./certs/cert.crt:/etc/x509/https/tls.crt"
            - "./certs/cert.key:/etc/x509/https/tls.key"

    mysql:
        image: mysql
        container_name: mysql
        networks:
            - keycloak-network
        environment:
            - MYSQL_DATABASE=keycloak
            - MYSQL_USER=keycloak
            - MYSQL_PASSWORD=keycloakpw
            - MYSQL_ROOT_PASSWORD=rootpw

networks:
    keycloak-network:
